log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_type debug

allow_anonymous false
password_file /mosquitto/config/users.txt

# Standart MQTT TCP Listener
listener 2883 0.0.0.0
protocol mqtt

# WebSockets Listener
listener 2884 0.0.0.0
protocol websockets
